# application.yml

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/boot_study
    username: boot
    password: 1234
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # ???? ?? ??? ?? ???? (production ????? 'none' ??)
    show-sql: true  # SQL ?? ?? ??
    properties:
      hibernate:
        format_sql: true  # SQL ?? ??? ??

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false  # ?? ??? ?? ????, production ????? true? ??

server:
  port: 8080  # ?????? ?? ?? ?? (??? 8080)

# ?? ??
logging:
  level:
    org.hibernate.SQL: debug  # Hibernate SQL ?? ?? ??
    org.hibernate.type.descriptor.sql.BasicBinder: trace  # SQL ???? ??? ?? ?? ??
