# application.yml

spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${ SPRING_DATASOURCE_USERNAME }
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    cache: false

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace

brawlstars:
  api:
    playerUrl: https://api.brawlstars.com/v1/players/
    token: ${BRAWLSTARS_API_TOKEN}